/**
 * Marine path mapper: MarineData to a Signal K values delta plus a one-shot
 * meta delta.
 *
 * Sea surface temperature maps to the canonical `environment.water.temperature`
 * leaf and surface current to the canonical `environment.current` OBJECT node
 * ({ drift, setTrue }); both are model values, so the delta is stamped with a
 * distinct marine `$source` and yields to a real sensor under source
 * priorities. Wave and swell are producer-namespaced under
 * `environment.water.waves.*` / `swell.*` (no canonical vocabulary exists) and
 * carry meta so the data browser renders them with units and labels.
 */

import type { Delta, Meta, PathValue, SourceRef } from '@signalk/server-api';
import { SIGNALK_PATHS } from '../constants/index.js';
import type { Logger, MarineData } from '../types/index.js';
import {
  buildMetaDelta as buildSkMetaDelta,
  buildValuesDelta,
  me,
  pv,
  toSourceRef,
} from '../utils/skDelta.js';

const WATER = SIGNALK_PATHS.ENVIRONMENT.WATER;

/** Default `$source` for marine model data, distinct so users can deprioritize it. */
export const MARINE_SOURCE: SourceRef = toSourceRef('open-meteo-marine');

/** Meta for the producer-namespaced wave and swell leaves (non-canonical vocabulary). */
const MARINE_META: ReadonlyArray<Meta> = [
  me(WATER.WAVE_SIGNIFICANT_HEIGHT, {
    units: 'm',
    displayName: 'Significant wave height',
    description: 'Mean height of the highest third of waves (combined wind-wave and swell).',
  }),
  me(WATER.WAVE_PERIOD, {
    units: 's',
    displayName: 'Wave period',
    description: 'Mean wave period.',
  }),
  me(WATER.WAVE_DIRECTION, {
    units: 'rad',
    displayName: 'Wave direction',
    description: 'Mean direction waves come FROM, true north.',
  }),
  me(WATER.WIND_WAVE_HEIGHT, {
    units: 'm',
    displayName: 'Wind-wave height',
    description: 'Height of locally wind-generated waves, excluding swell.',
  }),
  me(WATER.SWELL_HEIGHT, {
    units: 'm',
    displayName: 'Swell height',
    description: 'Height of swell (waves generated by distant weather).',
  }),
  me(WATER.SWELL_PERIOD, {
    units: 's',
    displayName: 'Swell period',
    description: 'Mean swell period.',
  }),
  me(WATER.SWELL_DIRECTION, {
    units: 'rad',
    displayName: 'Swell direction',
    description: 'Direction swell comes FROM, true north.',
  }),
];

export class MarinePathMapper {
  private readonly logger: Logger;
  private readonly sourceRef: SourceRef;

  constructor(logger: Logger = () => {}, sourceRef: SourceRef = MARINE_SOURCE) {
    this.logger = logger;
    this.sourceRef = sourceRef;
  }

  /** Map MarineData to a values delta. Emits only the fields the model provided. */
  public mapToSignalKPaths(marine: MarineData): Delta {
    const values: PathValue[] = [];

    if (marine.seaSurfaceTemperature !== undefined) {
      values.push(pv(WATER.TEMPERATURE, marine.seaSurfaceTemperature));
    }

    // environment.current is a single object node, not dotted leaves.
    if (marine.surfaceCurrentSpeed !== undefined || marine.surfaceCurrentDirection !== undefined) {
      const current: { drift?: number; setTrue?: number } = {
        ...(marine.surfaceCurrentSpeed !== undefined && { drift: marine.surfaceCurrentSpeed }),
        ...(marine.surfaceCurrentDirection !== undefined && {
          setTrue: marine.surfaceCurrentDirection,
        }),
      };
      values.push(pv(SIGNALK_PATHS.ENVIRONMENT.CURRENT, current));
    }

    if (marine.significantWaveHeight !== undefined) {
      values.push(pv(WATER.WAVE_SIGNIFICANT_HEIGHT, marine.significantWaveHeight));
    }
    if (marine.wavePeriod !== undefined) values.push(pv(WATER.WAVE_PERIOD, marine.wavePeriod));
    if (marine.waveDirection !== undefined) {
      values.push(pv(WATER.WAVE_DIRECTION, marine.waveDirection));
    }
    if (marine.windWaveHeight !== undefined) {
      values.push(pv(WATER.WIND_WAVE_HEIGHT, marine.windWaveHeight));
    }
    if (marine.swellHeight !== undefined) values.push(pv(WATER.SWELL_HEIGHT, marine.swellHeight));
    if (marine.swellPeriod !== undefined) values.push(pv(WATER.SWELL_PERIOD, marine.swellPeriod));
    if (marine.swellDirection !== undefined) {
      values.push(pv(WATER.SWELL_DIRECTION, marine.swellDirection));
    }

    this.logger('debug', 'Marine path mapping completed', { totalPaths: values.length });
    return buildValuesDelta(values, marine.timestamp, this.sourceRef);
  }

  /** One-shot meta delta for the producer-namespaced wave and swell leaves. */
  public buildMetaDelta(): Delta {
    return buildSkMetaDelta([...MARINE_META], this.sourceRef);
  }
}
